source "https://rubygems.org"
gem 'rails'
gem 'bootsnap'
gem 'sass-rails'
gem 'uglifier'
gem 'jquery-rails'
gem 'jbuilder'
gem 'mongoid'
gem 'dry-container'
gem 'dry-auto_inject'
gem 'redis'
gem 'redis-namespace'
gem 'redis-rails'
gem 'redis-rack-cache'
gem 'sidekiq'
gem 'devise'
gem 'kaminari-mongoid'
gem 'kaminari-actionview'
gem 'webpacker', '~> 3.5'
gem 'figaro'
gem 'capistrano'
group :development, :test do
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'byebug', platform: :mri
  gem 'web-console'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end
